name = "forge-app"
main = "dist/_worker.js"
compatibility_date = "2025-01-01"

# Enable the workers.dev domain for testing
workers_dev = false

# Set the custom domains
routes = [
  { pattern = "forgehive.dev", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[assets]
directory = "./dist/public"
binding = "ASSETS"